<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Catalog.Application/PucCrypto.Catalog.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/PucCrypto.BuildingBlocks.Messaging/PucCrypto.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
