<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Catalog.Application/PucCrypto.Catalog.Application.csproj" />
    <ProjectReference Include="../BuildingBlocks/PucCrypto.BuildingBlocks.Messaging/PucCrypto.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PucCrypto.Catalog.UnitTests" />
  </ItemGroup>

</Project>
