<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Catalog.Domain/PucCrypto.Catalog.Domain.csproj" />
    <ProjectReference Include="../BuildingBlocks/PucCrypto.BuildingBlocks.Abstractions/PucCrypto.BuildingBlocks.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PucCrypto.Catalog.UnitTests" />
  </ItemGroup>

</Project>
