<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.MarketData.Application/PucCrypto.MarketData.Application.csproj" />
    <ProjectReference Include="../PucCrypto.MarketData.Infrastructure/PucCrypto.MarketData.Infrastructure.csproj" />
  </ItemGroup>

</Project>
