<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Prediction.Application/PucCrypto.Prediction.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/PucCrypto.BuildingBlocks.Messaging/PucCrypto.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
