<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Forecast.Domain/PucCrypto.Forecast.Domain.csproj" />
    <ProjectReference Include="../BuildingBlocks/PucCrypto.BuildingBlocks.Abstractions/PucCrypto.BuildingBlocks.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PucCrypto.Forecast.UnitTests" />
  </ItemGroup>

</Project>
