<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Identity.Application/PucCrypto.Identity.Application.csproj" />
    <ProjectReference Include="../PucCrypto.Identity.Infrastructure/PucCrypto.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
