<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../PucCrypto.Prediction.Application/PucCrypto.Prediction.Application.csproj" />
    <ProjectReference Include="../PucCrypto.Prediction.Infrastructure/PucCrypto.Prediction.Infrastructure.csproj" />
  </ItemGroup>

</Project>
